/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_p2pvpn_tuntap_TunTapWindows */

#ifndef _Included_org_p2pvpn_tuntap_TunTapWindows
#define _Included_org_p2pvpn_tuntap_TunTapWindows
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_p2pvpn_tuntap_TunTapWindows
 * Method:    openTun
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_p2pvpn_tuntap_TunTapWindows_openTun
  (JNIEnv *, jobject);

/*
 * Class:     org_p2pvpn_tuntap_TunTapWindows
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_p2pvpn_tuntap_TunTapWindows_close
  (JNIEnv *, jobject);

/*
 * Class:     org_p2pvpn_tuntap_TunTapWindows
 * Method:    write
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_org_p2pvpn_tuntap_TunTapWindows_write
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     org_p2pvpn_tuntap_TunTapWindows
 * Method:    read
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_org_p2pvpn_tuntap_TunTapWindows_read
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
